using System;
using CUE4Parse.UE4.Writers;
using CUE4Parse_Conversion.ActorX;

namespace CUE4Parse_Conversion.Animations.PSA
{
    /** Binary bone format to deal with raw animations as generated by various exporters. */
    public class FNamedBoneBinary
    {
        private const int PskNameLength = 64;
        
        /** Bone's name */
        public string Name;
        /** reserved */
        public uint Flags;
        public int NumChildren;
        /** 0/NULL if this is the root bone. */
        public int ParentIndex;
        public VJointPosPsk BonePos;

        public void Serialize(FArchiveWriter Ar)
        {
            var truncatedName = Name[..Math.Min(Name.Length, PskNameLength)];
            Ar.Write(truncatedName, PskNameLength);
            Ar.Write(Flags);
            Ar.Write(NumChildren);
            Ar.Write(ParentIndex);
            BonePos.Serialize(Ar);
        }
    }
}
